Basic concepts assignments problem 2
Haider0007/Assignments pull request #2
Opened 2019-07-11 12:26 UTC by Haider0007

2019-07-11 16:08 UTC, wqsaali commented
@Haider0007 please add problem/question detail in description

2019-07-23 11:01 UTC, wqsaali requested changes

2019-07-23 11:01 UTC, wqsaali commented on problem2.rb
> +valid_num=false
```
input_number=Integer(gets.chomp!)
if input_number.negative?
  puts 'Wrong Input! Please Enter Again'
else
  1.upto(input_number) do |x|
    puts alphabet * x
  end
end

2019-07-23 11:01 UTC, wqsaali commented on problem2.rb
> +  puts "Wrong Input! Please Enter Again" unless valid_num
if you have only string then use single quote.
double quote do two things. 
1. Interpolation
2. Save string.
That's why it is costly as compared to single quote

2019-07-23 11:01 UTC, wqsaali commented on problem2.rb
> +  puts "Enter number of copies to create:"
use single quote for string

2019-07-23 11:01 UTC, wqsaali commented on problem2.rb
> +  puts alphabet * Integer(x)
no need to explicity convert to Integer as x is already an integer

Instead of `x` variable name should be `index`

2019-07-23 16:18 UTC, Haider0007 commented on problem2.rb
> +valid_num=false
I have uploaded updated solution and 'until' is used in the solution for taking input from user till he enters some valid input.

2019-07-30 06:09 UTC, merged