solve problem 3
Haider0007/Assignments pull request #3
Opened 2019-07-11 12:42 UTC by Haider0007

Basic_Problem_3

2019-07-11 16:08 UTC, wqsaali commented
please add problem/question detail in description @Haider0007

2019-07-23 11:07 UTC, wqsaali requested changes

2019-07-23 11:07 UTC, wqsaali commented on 3/problem3.rb
> +puts year%4==0 && year%400==0? "Year is leap" : "Year is not leap"
Instead use Ruby Date library
https://ruby-doc.org/stdlib-2.3.1/libdoc/date/rdoc/Date.html#method-c-leap-3F
require 'Date' # at beginning
`Date.leap?(year) ?  'yes' : 'no'`

2019-07-23 16:31 UTC, Haider0007 commented
Solution has been updated...

2019-07-30 06:10 UTC, merged